kind: pipeline
type: exec
name: Check main branch

platform:
  os: linux
  arch: amd64

steps:
  - name: sync repo
    commands:
      - git remote add upstream https://github.com/Jopyth/MMM-Remote-Control.git
      - git fetch upstream
      - git rebase upstream/master
      - git remote set-url origin git@github.com:dangherve/MMM-Remote-Control.git
      - git push --force --set-upstream origin master

