---
kind: pipeline
type: exec
name: cronRebaseDevelop

platform:
  os: linux
  arch: amd64

trigger:
    branch:
        include:
            - master

steps:
  - name: sync repo
    commands:
      - git remote add upstream https://github.com/Jopyth/MMM-Remote-Control.git
      - git fetch upstream
      - git rebase upstream/master
      - git remote set-url origin git@github.com:dangherve/MMM-Remote-Control.git
      - git push --force --set-upstream origin master

---
kind: pipeline
type: exec
name: rebaseDevelop

platform:
  os: linux
  arch: amd64

trigger:
    branch:
        exclude:
            - master

steps:
  - name: sync repo
    commands:
      - git remote add upstream https://github.com/Jopyth/MMM-Remote-Control.git
      - git status
      - git checkout master
      - git fetch upstream
      - git rebase upstream/master
      - git remote set-url origin git@github.com:dangherve/MMM-Remote-Control.git
      - git push --force --set-upstream origin master
